# Sin HTTPS
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: socaps-hub-ingress
# spec:
#   rules:
#     - http:
#         paths:
#         - path: /*
#           pathType: ImplementationSpecific
#           backend:
#             service:
#               name: client-gateway
#               port:
#                 number: 3000

# Con HTTPS:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socaps-hub-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - api.socaps-hub.enfoquecooperativo.com
      secretName: socapshub-tls2  # Nombre del Secret TLS creado con el .crt y .key
  rules:
    - host: api.socaps-hub.enfoquecooperativo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-gateway     # Reemplaza con el nombre real del servicio backend
                port:
                  number: 3000             # Puerto expuesto por tu servicio

