apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/socaps-hub-dev-466500/image-registry/client-gateway
        name: client-gateway
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources:
          requests:
            cpu: "100m"         # ðŸ”½ solicita poco CPU
            memory: "512Mi"     # ðŸ”½ solicita menos RAM
          limits:
            cpu: "250m"         # ðŸ”¼ hasta cuÃ¡nto puede usar
            memory: "1Gi"      # ðŸ”¼ lÃ­mite de memoria
status: {}
