apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: supervision-ms
  name: supervision-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supervision-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: supervision-ms
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/socaps-hub-dev/image-registry/supervision-ms
        name: supervision-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: socaps-hub-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef:
              name: socaps-hub-secrets
              key: jwt_secret
        resources: {}
status: {}
