apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: config-ms
  name: config-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-ms
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/socaps-hub-dev/image-registry/config-ms
        name: config-ms
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: socaps-hub-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef:
              name: socaps-hub-secrets
              key: jwt_secret
        resources: {}
status: {}
